#!/usr/bin/env python3
"""Turns a text file into a C source holding it as a string constant, byte for byte.

Usage: mk_text.py <text file> <output .c> <symbol>
"""

import sys


def main(argv):
    with open(argv[1], "rb") as f:
        data = f.read()
    out = ["/* Autogenerated by mk_text.py from %s */\n" % argv[1],
           "const char %s[] =\n" % argv[3]]
    for line in data.splitlines(keepends=True):
        chunk = ""
        for b in line:
            if b == 0x22 or b == 0x5c:
                chunk += "\\" + chr(b)
            elif 0x20 <= b < 0x7f:
                chunk += chr(b)
            else:
                chunk += "\\%03o" % b
        out.append('    "%s"\n' % chunk)
    out.append("    ;\n")
    with open(argv[2], "w", newline="\n") as f:
        f.write("".join(out))


if __name__ == "__main__":
    main(sys.argv)
