#!/bin/bash

# Installs the tools needed to build FlashFloppy on Ubuntu 22.04 into a directory of their own,
# without root and without touching the system: the Arm GNU toolchain from Arm's tarball, and
# srecord plus the Python modules crcmod and intelhex from Ubuntu packages that are downloaded
# and unpacked, not installed. Rerunning skips whatever is already in place; deleting the
# directory uninstalls everything.
#
# Usage: set_up_tools.sh

# Written with the help of Claude Fable 5.1.

set -o pipefail

: "${TOOLS_DIR="${HOME}/retro/flashfloppy-tools"}"  # Where everything is installed.

# The compiler release packaged as gcc-arm-none-eabi 15:10.3-2021.07-4 in Ubuntu 22.04, which
# the upstream CI builds with.
readonly GCC_NAME="gcc-arm-none-eabi-10.3-2021.07"
readonly GCC_ARCHIVE="${GCC_NAME}-x86_64-linux.tar.bz2"
# Arm's own storage host, which the links on developer.arm.com redirect to.
readonly GCC_URL_DIR="https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.07"
readonly GCC_SHA256="8c5b8de344e23cd035ca2b53bbf2075c58131ad61223cae48510641d3e556cea"

# Ubuntu packages to unpack: srec_cat with its library, and the Python modules.
readonly DEB_PACKAGES=(srecord libsrecord0 python3-crcmod python3-intelhex)

readonly DOWNLOADS_DIR="${TOOLS_DIR}/downloads"
readonly SYSROOT_DIR="${TOOLS_DIR}/sysroot"
readonly ENV_FILE="${TOOLS_DIR}/env.sh"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

install_gcc() {
  local -r archive="${DOWNLOADS_DIR}/${GCC_ARCHIVE}"

  if [[ -x "${TOOLS_DIR}/${GCC_NAME}/bin/arm-none-eabi-gcc" ]]; then
    echo "${GCC_NAME}: already installed"
    return
  fi

  if [[ ! -f "${archive}" ]]; then
    echo "${GCC_NAME}: downloading"
    wget --no-verbose --show-progress -O "${archive}.part" "${GCC_URL_DIR}/${GCC_ARCHIVE}" \
        || fail "Cannot download ${GCC_URL_DIR}/${GCC_ARCHIVE}"
    mv "${archive}.part" "${archive}" || fail "Cannot rename ${archive}.part"
  fi

  echo "${GCC_SHA256}  ${archive}" | sha256sum --check --quiet \
      || fail "Wrong checksum of ${archive}; delete it to download again."

  echo "${GCC_NAME}: unpacking"
  tar -xjf "${archive}" -C "${TOOLS_DIR}" || fail "Cannot unpack ${archive}"
}

install_debs() {
  local -r debs_dir="${DOWNLOADS_DIR}/debs"
  local deb

  if [[ -x "${SYSROOT_DIR}/usr/bin/srec_cat" ]]; then
    echo "${DEB_PACKAGES[*]}: already installed"
    return
  fi

  echo "${DEB_PACKAGES[*]}: downloading"
  mkdir -p "${debs_dir}" || fail "Cannot create ${debs_dir}/"
  (cd "${debs_dir}" && apt-get download "${DEB_PACKAGES[@]}") \
      || fail "Cannot download the Ubuntu packages."

  mkdir -p "${SYSROOT_DIR}" || fail "Cannot create ${SYSROOT_DIR}/"
  for deb in "${debs_dir}"/*.deb; do
    echo "Unpacking $(basename "${deb}")"
    dpkg -x "${deb}" "${SYSROOT_DIR}" || fail "Cannot unpack ${deb}"
  done
}

write_env_file() {
  cat >"${ENV_FILE}" <<EOF || fail "Cannot write ${ENV_FILE}"
# Generated by set_up_tools.sh. Source it to make the FlashFloppy build tools available.
export PATH="${TOOLS_DIR}/${GCC_NAME}/bin:${SYSROOT_DIR}/usr/bin:\${PATH}"
export LD_LIBRARY_PATH="${SYSROOT_DIR}/usr/lib/x86_64-linux-gnu:\${LD_LIBRARY_PATH}"
export PYTHONPATH="${SYSROOT_DIR}/usr/lib/python3/dist-packages:\${PYTHONPATH}"
EOF
}

# Runs each tool once, in a subshell so that the environment of the caller is left alone.
check_tools() (
  source "${ENV_FILE}" || fail "Cannot read ${ENV_FILE}"
  arm-none-eabi-gcc --version | head -n 1 || fail "arm-none-eabi-gcc does not run."
  srec_cat --version | head -n 1 || fail "srec_cat does not run."
  python3 -c 'import crcmod, intelhex; print("Python modules: crcmod, intelhex")' \
      || fail "The Python modules do not load."
)

main() {
  mkdir -p "${DOWNLOADS_DIR}" || fail "Cannot create ${DOWNLOADS_DIR}/"
  install_gcc
  install_debs
  write_env_file
  check_tools || exit 1
  echo "Tools are ready in ${TOOLS_DIR}/"
}

main "$@"
